var chip_names = ["VMB","Submarine","Tr","Tk","Krpl","Str","Asmin","R","Kraser","Lincor","Avia","Br","Torpeda","Mine","Sm","Aircraft","AtomBomb",]
var chip_pictures = new Array ();
chip_pictures[0] ="resources/images/VMB.jpg" ;
chip_pictures[1] ="resources/images/Submarine.jpg" ;
chip_pictures[2] ="resources/images/Tr.jpg" ;
chip_pictures[3] ="resources/images/Tk.jpg" ;
chip_pictures[4] ="resources/images/Krpl.jpg" ;
chip_pictures[5] ="resources/images/Str.jpg" ;
chip_pictures[6] ="resources/images/Asmin.jpg" ;
chip_pictures[7] ="resources/images/R.jpg" ;
chip_pictures[8] ="resources/images/Kraser.jpg" ;
chip_pictures[9] ="resources/images/Lincor.jpg" ;
chip_pictures[10] ="resources/images/Avia.jpg" ;
chip_pictures[11] ="resources/images/Br.jpg" ;
chip_pictures[12] ="resources/images/Torpeda.jpg" ;
chip_pictures[13] ="resources/images/Mine.jpg" ;
chip_pictures[14] ="resources/images/Sm.jpg" ;
chip_pictures[15] ="resources/images/Aircraft.jpg" ;
chip_pictures[16] ="resources/images/AtomBomb.jpg" ;

var chip_amount = [1, 3, 2, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0];//тест
//var chip_amount = [2, 6, 6, 6, 1, 6, 6, 2, 6, 2, 1, 1, 6, 6, 1, 1, 1];//полный контеннт
